---
title: "Supporting Materials: Estuary GAM Model Assessment"
author: "Michael Schramm"
---

# Modeling Approach

Site-specific Generalized Additive Models (GAMs) were developed for Nitrate-Nitrogen (NO~3~-N) and Total Phosphorus (TP). 


# Model Results



```{r}
#| echo: false
#| message: false
#| warning: false

options(tidyverse.quiet=TRUE)
library(targets)

source("../../_targets_packages.R")

## targets
store = "../../_targets"

```

### Total Phosphorus

#### TCEQ-13563

```{r}
#| echo: false
#| tbl-cap: "Temporal TP model TCEQ-13563."

tar_read(tp_lavaca_13563_temporal, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal TP model TCEQ-13563."
tar_read(tp_lavaca_13563_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow TP model TCEQ-13563."

tar_read(tp_lavaca_13563_flow, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow TP model TCEQ-13563."
tar_read(tp_lavaca_13563_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full TP model TCEQ-13563."

tar_read(tp_lavaca_13563_full, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full TP model TCEQ-13563."
tar_read(tp_lavaca_13563_full, store = store)  |> 
  gratia::appraise()
```

#### TCEQ-13383

```{r}
#| echo: false
#| tbl-cap: "Temporal TP model TCEQ-13383."

tar_read(tp_lavaca_13383_temporal, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal TP model TCEQ-13383."
tar_read(tp_lavaca_13383_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow TP model TCEQ-13383."

tar_read(tp_lavaca_13383_flow, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow TP model TCEQ-13383."
tar_read(tp_lavaca_13383_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full TP model TCEQ-13383."

tar_read(tp_lavaca_13383_full, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full TP model TCEQ-13383."
tar_read(tp_lavaca_13383_full, store = store)  |> 
  gratia::appraise()
```

#### TCEQ-13384

```{r}
#| echo: false
#| tbl-cap: "Temporal TP model TCEQ-13384."

tar_read(tp_lavaca_13384_temporal, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal TP model TCEQ-13384."
tar_read(tp_lavaca_13384_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow TP model TCEQ-13384."

tar_read(tp_lavaca_13384_flow, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow TP model TCEQ-13384."
tar_read(tp_lavaca_13384_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full TP model TCEQ-13384."

tar_read(tp_lavaca_13384_full, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full TP model TCEQ-13384."
tar_read(tp_lavaca_13384_full, store = store)  |> 
  gratia::appraise()
```


### Nitrite + Nitrate

#### TCEQ-13563

```{r}
#| echo: false
#| tbl-cap: "Temporal Nitrite+Nitrate model TCEQ-13563."

tar_read(no3_lavaca_13563_temporal, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal Nitrite+Nitrate model TCEQ-13563."
tar_read(no3_lavaca_13563_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow Nitrite+Nitrate model TCEQ-13563."

tar_read(no3_lavaca_13563_flow, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow Nitrite+Nitrate model TCEQ-13563."
tar_read(no3_lavaca_13563_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full Nitrite+Nitrate model TCEQ-13563."

tar_read(no3_lavaca_13563_full, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full Nitrite+Nitrate model TCEQ-13563."
tar_read(no3_lavaca_13563_full, store = store)  |> 
  gratia::appraise()
```

#### TCEQ-13383

```{r}
#| echo: false
#| tbl-cap: "Temporal Nitrite+Nitrate model TCEQ-13383."

tar_read(no3_lavaca_13383_temporal, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal Nitrite+Nitrate model TCEQ-13383."
tar_read(no3_lavaca_13383_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow Nitrite+Nitrate model TCEQ-13383."

tar_read(no3_lavaca_13383_flow, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow Nitrite+Nitrate model TCEQ-13383."
tar_read(no3_lavaca_13383_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full Nitrite+Nitrate model TCEQ-13383."

tar_read(no3_lavaca_13383_full, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full Nitrite+Nitrate model TCEQ-13383."
tar_read(no3_lavaca_13383_full, store = store)  |> 
  gratia::appraise()
```

#### TCEQ-13384

```{r}
#| echo: false
#| tbl-cap: "Temporal Nitrite+Nitrate model TCEQ-13384."

tar_read(no3_lavaca_13384_temporal, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal Nitrite+Nitrate model TCEQ-13384."

tar_read(no3_lavaca_13384_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow Nitrite+Nitrate model TCEQ-13384."

tar_read(no3_lavaca_13384_flow, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow Nitrite+Nitrate model TCEQ-13384."

tar_read(no3_lavaca_13384_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full Nitrite+Nitrate model TCEQ-13384."

tar_read(no3_lavaca_13384_full, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full Nitrite+Nitrate model TCEQ-13384."

tar_read(no3_lavaca_13384_full, store = store)  |> 
  gratia::appraise()
```

### Chlorophyll-a

#### TCEQ-13563

```{r}
#| echo: false
#| tbl-cap: "Temporal chlorophyll-a model TCEQ-13563."

tar_read(chla_lavaca_13563_temporal, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal chlorophyll-a model TCEQ-13563."

tar_read(chla_lavaca_13563_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow chlorophyll-a model TCEQ-13563."

tar_read(chla_lavaca_13563_flow, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow chlorophyll-a model TCEQ-13563."

tar_read(chla_lavaca_13563_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full chlorophyll-a model TCEQ-13563."

tar_read(chla_lavaca_13563_full, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full chlorophyll-a model TCEQ-13563."
tar_read(chla_lavaca_13563_full, store = store)  |> 
  gratia::appraise()
```

#### TCEQ-13383

```{r}
#| echo: false
#| tbl-cap: "Temporal chlorophyll-a model TCEQ-13383."

tar_read(chla_lavaca_13383_temporal, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal chlorophyll-a model TCEQ-13383."

tar_read(chla_lavaca_13383_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow chlorophyll-a model TCEQ-13383."

tar_read(chla_lavaca_13383_flow, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow chlorophyll-a model TCEQ-13383."

tar_read(chla_lavaca_13383_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full chlorophyll-a model TCEQ-13383."

tar_read(chla_lavaca_13383_full, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full chlorophyll-a model TCEQ-13383."
tar_read(chla_lavaca_13383_full, store = store)  |> 
  gratia::appraise()
```

#### TCEQ-13384

```{r}
#| echo: false
#| tbl-cap: "Temporal chlorophyll-a model TCEQ-13384."

tar_read(chla_lavaca_13384_temporal, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal chlorophyll-a model TCEQ-13384."
tar_read(chla_lavaca_13384_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow chlorophyll-a model TCEQ-13384."

tar_read(chla_lavaca_13384_flow, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow chlorophyll-a model TCEQ-13384."
tar_read(chla_lavaca_13384_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full chlorophyll-a model TCEQ-13384."

tar_read(chla_lavaca_13384_full, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full chlorophyll-a model TCEQ-13384."
tar_read(chla_lavaca_13384_full, store = store)  |> 
  gratia::appraise()
```



### Dissolved Oxygen

#### TCEQ-13563

```{r}
#| echo: false
#| tbl-cap: "Temporal DO model TCEQ-13563."

tar_read(do_lavaca_13563_temporal, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal DO model TCEQ-13563."

tar_read(do_lavaca_13563_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow DO model TCEQ-13563."

tar_read(do_lavaca_13563_flow, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow DO model TCEQ-13563."

tar_read(do_lavaca_13563_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full DO model TCEQ-13563."

tar_read(do_lavaca_13563_full, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full DO model TCEQ-13563."
tar_read(do_lavaca_13563_full, store = store)  |> 
  gratia::appraise()
```

#### TCEQ-13383

```{r}
#| echo: false
#| tbl-cap: "Temporal DO model TCEQ-13383."

tar_read(do_lavaca_13383_temporal, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal DO model TCEQ-13383."

tar_read(do_lavaca_13383_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow DO model TCEQ-13383."

tar_read(do_lavaca_13383_flow, store = store) |> 
  as_flextable()
```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow DO model TCEQ-13383."

tar_read(do_lavaca_13383_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full DO model TCEQ-13383."

tar_read(do_lavaca_13383_full, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full DO model TCEQ-13383."
tar_read(do_lavaca_13383_full, store = store)  |> 
  gratia::appraise()
```

#### TCEQ-13384

```{r}
#| echo: false
#| tbl-cap: "Temporal DO model TCEQ-13384."

tar_read(do_lavaca_13384_temporal, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics temporal DO model TCEQ-13384."
tar_read(do_lavaca_13384_temporal, store = store)  |> 
  gratia::appraise()
```


```{r}
#| echo: false
#| tbl-cap: "Flow DO model TCEQ-13384."

tar_read(do_lavaca_13384_flow, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics flow DO model TCEQ-13384."
tar_read(do_lavaca_13384_flow, store = store)  |> 
  gratia::appraise()
```

```{r}
#| echo: false
#| tbl-cap: "Full DO model TCEQ-13384."

tar_read(do_lavaca_13384_full, store = store) |> 
  as_flextable()

```


```{r}
#| echo: false
#| fig-cap: "Resdidual diagnostics full DO model TCEQ-13384."
tar_read(do_lavaca_13384_full, store = store)  |> 
  gratia::appraise()
```

# Model comparison

Compare the AIC scores.

```{r}
#| echo: false

flextable::flextable(
  dplyr::bind_rows(
    tar_read(tp_13563, store = store), 
    tar_read(tp_13383, store = store),
    tar_read(tp_13384, store = store),
    tar_read(no3_13563, store = store), 
    tar_read(no3_13383, store = store),
    tar_read(no3_13384, store = store),
    tar_read(chla_13563, store = store), 
    tar_read(chla_13383, store = store),
    tar_read(chla_13384, store = store),
    tar_read(do_13563, store = store), 
    tar_read(do_13383, store = store),
    tar_read(do_13384, store = store)
    )) |> 
  flextable::hline(i = c(3,6,9)) |> 
  flextable::merge_v(j = 1) |> 
  flextable::footnote(i = c(1:12),
                      j = c(5, 5, 4,
                            5, 4, 4,
                            4, 3, 3,
                            4, 3, 3),
                      value = as_paragraph(
                        "Selected model"),
                      ref_symbols = "*")
```


## 